#!/usr/bin/env node
/**
 * 构建前钩子脚本
 * 处理原生模块兼容性问题
 */

const fs = require('fs');
const path = require('path');

console.log('Running before-build script...');

// 检查是否需要替换 sqlite3
const sqlite3Path = path.join(__dirname, '..', 'node_modules', 'sqlite3');
const betterSqlite3Path = path.join(__dirname, '..', 'node_modules', 'better-sqlite3');

// 如果 better-sqlite3 存在，使用它替代 sqlite3
if (fs.existsSync(betterSqlite3Path)) {
  console.log('better-sqlite3 found, will use it instead of sqlite3');
}

// 创建兼容层
const shimDir = path.join(__dirname, '..', 'src', 'db-shim');
if (!fs.existsSync(shimDir)) {
  fs.mkdirSync(shimDir, { recursive: true });
}

// 写入兼容代码
const shimCode = `
// Database compatibility shim
// Auto-generated by before-build.js

try {
  // Try better-sqlite3 first (prebuilt binaries available)
  const Database = require('better-sqlite3');
  module.exports = {
    Database: class extends Database {
      constructor(path, options) {
        super(path, options);
      }
      
      // sqlite3 compatible API
      run(sql, params, callback) {
        try {
          const stmt = this.prepare(sql);
          const result = stmt.run(params);
          if (callback) callback(null, result);
          return result;
        } catch (err) {
          if (callback) callback(err);
          throw err;
        }
      }
      
      get(sql, params, callback) {
        try {
          const stmt = this.prepare(sql);
          const result = stmt.get(params);
          if (callback) callback(null, result);
          return result;
        } catch (err) {
          if (callback) callback(err);
          throw err;
        }
      }
      
      all(sql, params, callback) {
        try {
          const stmt = this.prepare(sql);
          const result = stmt.all(params);
          if (callback) callback(null, result);
          return result;
        } catch (err) {
          if (callback) callback(err);
          throw err;
        }
      }
      
      close(callback) {
        this.close();
        if (callback) callback();
      }
    },
    verbose: () => module.exports
  };
} catch (e) {
  // Fall back to sqlite3
  console.log('better-sqlite3 not available, using sqlite3');
  module.exports = require('sqlite3');
}
`;

fs.writeFileSync(path.join(shimDir, 'index.js'), shimCode);
console.log('Database shim created successfully');

// 设置环境变量避免编译
process.env.npm_config_build_from_source = 'false';
process.env.npm_config_disturl = 'https://electronjs.org/headers';

console.log('before-build script completed');
